
development_not_relational:
  access_key_id: your_access_key
  secret_access_key: your_secret_key
  domain_name: test
  s3_bucket: test_test
  sqs_work_queue: test_work_queue_test
  base_domain_name: NotRelational_testing
  repository_class: NotRelational::SdbRepository

testing_not_relational:
  aws_key_id: your_access_key
  aws_secret_key: your_secret_key
  base_domain_name: test_test
  s3_clob_bucket: alnitakTest
  sqs_work_queue: test_work_queue_test
  use_seperate_domain_per_model: false
  fail_fast: true
  repository_class: NotRelational::SdbRepository
  cipher_key_file: /tmp/cipher_key
  cipher_iv_file: /tmp/cipher_iv

memcache_testing_not_relational:
  aws_key_id:
  aws_secret_key: a
  fail_fast: true
  base_domain_name: test_test
  s3_clob_bucket: alnitakTest
  sqs_work_queue: test_work_queue_test
  use_seperate_domain_per_model: false
  memcache_servers: ec2-75-101-213-239.compute-1.amazonaws.com:11211
  repository_class: NotRelational::MemcacheRepository
  
memcache_s3_testing_not_relational:
  aws_key_id: your_access_key
  aws_secret_key: your_secret_key
  base_domain_name: test_test
  s3_clob_bucket: alnitakTest
  sqs_work_queue: test_work_queue_test
  use_seperate_domain_per_model: false
  memcache_servers: ec2-75-101-213-239.compute-1.amazonaws.com:11211
  fail_fast: true
  repository_class: NotRelational::MemcacheRepository

production_not_relational:
  access_key_id: your_access_key
  secret_access_key: your_secret_key
  domain_name: test_test
  s3_bucket: test_test
  sqs_work_queue: devpay_app_work_queue
  repository_class: NotRelational::SdbRepository
  